version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"                   # Root directory where `go.mod` is located
    schedule:
      interval: "weekly"             # Checks for updates every week
    commit-message:
      prefix: "[deps]"               # Adds "deps" prefix to PR titles